### ISSUE TITLE
Define minio bucket policy

### ISSUE THREAD

**Issue by vickyfaizal** [codenergic/theskeleton#66]
Define minio bucket policy after creating bucket like this:

minioClient.setBucketPolicy(BUCKET_NAME, "*", PolicyType.READ_ONLY);

 *bucket name and policy type took from properties

**Comment by dianw** [comment]
My idea is change the ```buckets``` property in ```s3.client``` from just list of String to list of object. So we can define the property something like:
```yml
s3:
  client:
    buckets:
      - name: profile-pictures
        policy: READ_ONLY
      - name: another-bucket
        policy: WRITE_ONLY
```

https://github.com/codenergic/theskeleton/blob/1bd1d16758ecd6dbf9a7f90ca04504c7b68aab9a/src/main/java/org/codenergic/theskeleton/core/data/S3ClientConfig.java#L74
